Add requirements JSONs for WWS, COS-AB, and COS-BSE
TigerAppsOrg/TigerPath pull request #10
Opened 2018-04-13 16:46 UTC by bnehoran

2018-04-15 19:45 UTC, churichard requested changes
Nice work! I raised a couple of issues below.

2018-04-15 19:45 UTC, churichard commented on majors-and-certificates/majors/COS-AB_2018.json
> +            "COS 436: Human-Computer Interface Technology ",
There's an extra space at the end here

2018-04-15 19:45 UTC, churichard commented on majors-and-certificates/majors/COS-AB_2018.json
> +      "max_counted": null,
For independent work, should we still check for it and the user can manually tick off that they've satisfied it, or should we not check for it at all?

Also, are AB COS people not allowed to partake in an independent work seminar?

2018-04-15 19:45 UTC, churichard commented on majors-and-certificates/majors/COS-BSE_2018.json
> +        "COS 397",
If you do independent work as COS BSE, do you have to enroll in one of these courses even if you're not doing a seminar?

2018-04-15 19:45 UTC, churichard commented on majors-and-certificates/majors/WWS_2018.json
> +                    "AMS 311: Education and Inequality",
Why are you putting the elective courses here if you also have them in a separate file?

On that note, I just thought of something - what do you think of separating the courses that satisfy requirements from the actual json itself? If we separate them, the json would encode the structure of the requirements (which may change, but probably relatively infrequently), and there would be a separate file to store the courses (which would probably change more frequently). This would also mean that if someone were to update courses, they wouldn't need to dig through the structure of the json in order to do so. We already do this to a certain extent, like for LANG and distribution requirements - doing it for everything might increase maintainability.

Let me know what you think

2018-04-15 19:45 UTC, churichard commented on majors-and-certificates/majors/WWS_2018.json
> +
Earmarking this with the same issue raised above:

For senior thesis, should we still check for it and the user can manually tick off that they've satisfied it, or should we not check for it at all?

2018-04-15 19:45 UTC, churichard commented on majors-and-certificates/majors/WWS_2018.json
> +
Remove note

2018-04-15 19:45 UTC, churichard commented on majors-and-certificates/majors/WWS_2018.json
> +
Remove note

2018-04-15 19:45 UTC, churichard commented on majors-and-certificates/majors/WWS_2018.json
> +
Remove note

On that note, how are you checking these foreign language requirements in the req checker (i.e. how are you enforcing that LANG has to be different between these two inner branches (that check LANG 102, LANG 103, etc.) but that the LANG in these inner branches _can_ be the same as the LANG that checks for LANG 2** and LANG 3**)?

2018-04-15 19:45 UTC, churichard commented on majors-and-certificates/majors/WWS_2018.json
> +
Earmarking this with the same issue raised before:

For field experience, should we still check for it and the user can manually tick off that they've satisfied it, or should we not check for it at all?

2018-04-15 19:59 UTC, bnehoran commented on majors-and-certificates/majors/COS-BSE_2018.json
> +        "COS 397",
yes

2018-04-18 20:57 UTC, bnehoran commented on majors-and-certificates/majors/COS-AB_2018.json
> +            "COS 436: Human-Computer Interface Technology ",
Done

2018-04-18 21:12 UTC, bnehoran commented on majors-and-certificates/majors/COS-AB_2018.json
> +      "max_counted": null,
No. Only BSE students sign up for COS 397/398/497/498.

2018-04-18 21:13 UTC, bnehoran commented on majors-and-certificates/majors/COS-AB_2018.json
> +      "max_counted": null,
It will appear, and will be unsatisfiable, but also not required.

2018-04-18 21:18 UTC, bnehoran commented on majors-and-certificates/majors/WWS_2018.json
> +                    "AMS 311: Education and Inequality",
I think it might be useful to add that as an option.
I think I'll just make a note, and we can add it in later, since I don't think it's high priority.

2018-04-18 21:27 UTC, bnehoran commented on majors-and-certificates/majors/WWS_2018.json
> +
It's in place of a comment.

2018-04-18 21:28 UTC, bnehoran commented on majors-and-certificates/majors/WWS_2018.json
> +
Not sure. Need to think about it.

2018-04-18 21:29 UTC, bnehoran commented on majors-and-certificates/majors/WWS_2018.json
> +
Same response.

2018-04-18 22:27 UTC, churichard approved these changes

2018-04-18 22:53 UTC, merged