Add course search
TigerAppsOrg/TigerPath pull request #11
Opened 2018-04-15 21:45 UTC by danielleung27

/: webpack-stats files necessary for react. 

/tigerpath: Added urls to urls.py for search engine page (will integrate with front end later) and get request. Added get request function to views.py (get_courses) and implemented filter functions which creates a filtered list of courses to send to react end. Resources.py is currently not used but it is used for tastypie api just in case we need it later.

/tigerpath/templates/tigerpath: added search.html to display course searcher, will integrate with front end later 

/New folder: all files here are autogenerated bundles from react (I am not sure which file alters what this folder is named but currently it is automatically named New folder)

/frontend: all files here are for react. 

/frontend/src: These files are the more important ones. Search.js is the react code for the searching and Courses.js is a child to Search which displays the course cards. App.css and index.css are there for reference and will be modified later to style the react components. I'm not sure what registerServiceWorker.js is, it was provided when I set up react.

2018-04-17 03:01 UTC, churichard requested changes
Good work! Make sure to address the comments and also push your updated searching code.

2018-04-17 03:01 UTC, churichard commented on config/settings/base.py
> +WEBPACK_LOADER = {
Should probably be in development.py instead

2018-04-17 03:01 UTC, churichard commented on config/settings/production.py
> +STATICFILES_DIRS = [
Should probably be in base.py

2018-04-17 03:01 UTC, churichard commented on frontend/public/index.html
> +<!DOCTYPE html>
Is the stuff in frontend/public needed? I think we're probably serving stuff from the Django server, right?

2018-04-17 03:01 UTC, churichard commented on frontend/src/Courses.js
> +  {
Let's use the style of putting the brace on the same line as the function name (change this in the other js files you modified as well):
```
function() {
    # code here
}
```

2018-04-17 03:01 UTC, churichard commented on frontend/README.md
> +This project was bootstrapped with [Create React App](https://github.com/facebookincubator/create-react-app).
Delete this file

2018-04-17 03:01 UTC, churichard commented on New folder/New folder/asset-manifest.json
> +{
Delete all this New folder stuff

2018-04-17 03:01 UTC, churichard commented on frontend/.gitignore
> +# See https://help.github.com/ignore-files/ for more about ignoring files.
Move this into the root level .gitignore

2018-04-17 03:01 UTC, churichard commented on frontend/src/Courses.js
> +    console.info(this.props.course_list)
Don't print this out

2018-04-17 03:01 UTC, churichard commented on tigerpath/urls.py
> +    path('get_courses/<search_query>', views.get_courses, name='get_courses'),
This is part of the API right? I think a better URL might be 'api/v1/get_courses/<search_query>' (it makes it clear that it's part of the API and if we wanted, we could add a new URL in the future for v2 without breaking any apps that are using v1)

2018-04-17 03:01 UTC, churichard commented on webpack-stats.dev.json
> +{"status":"done","publicPath":"http://localhost:3000/","chunks":{"main":[{"name":"static/js/bundle.js","publicPath":"http://localhost:3000/static/js/bundle.js","path":"C:\\Users\\Daniel\\Desktop\\Cla
I don't particularly like the fact that this is tied to a path on your local computer, is there some way to fix this?

2018-04-17 03:01 UTC, churichard commented on tigerpath/views.py
> +            results = listing_to_course(results)
Does it take a long time to convert between courses and listings? This portion of the code seems a bit inefficient

2018-04-17 03:01 UTC, churichard commented on tigerpath/views.py
> +def filter_dept(query, results):
For these filtering functions, I think you can use Python's `filter` and pass in lambdas: http://book.pythontips.com/en/latest/map_filter.html#filter

2018-04-17 03:01 UTC, churichard commented on tigerpath/views.py
> +    for query in split_query:
I think the way you structure these regular expressions means that empty strings are occasionally added to the list of queries, e.g. when you split by spaces for "CEE " and "102A". I noticed you check for this when you're iterating through the queries but I think it would be cleaner to filter them out in this function (you can try using `filter(None, queries)`)

2018-04-17 03:01 UTC, churichard commented on tigerpath/views.py
> +            for course_listing in course.course_listing_set.all():
I think you can do `converted_results.extend(course.course_listing_set.all())` instead of having two for loops

2018-04-17 03:29 UTC, danielleung27 commented on frontend/public/index.html
> +<!DOCTYPE html>
For some reason, deleting these files causes an error in {% render_bundle 'main' %} line 12 in search.html

2018-04-17 05:36 UTC, danielleung27 commented on webpack-stats.dev.json
> +{"status":"done","publicPath":"http://localhost:3000/","chunks":{"main":[{"name":"static/js/bundle.js","publicPath":"http://localhost:3000/static/js/bundle.js","path":"C:\\Users\\Daniel\\Desktop\\Cla
This file is autogenerated when you start the react server

2018-04-17 07:04 UTC, danielleung27 commented on tigerpath/views.py
> +    for query in split_query:
The first part is in case the user combines the department and number. The for loop to split by spaces is if there are any extra queries. Like if the user did "cee102a eng" it will first split into ['cee', '102a eng'] and then it will go through and split into ['cee', '102a', 'eng']

2018-04-18 04:29 UTC, churichard approved these changes
How do you run this? Do you need to run a special command for React or can you just run the Django server and it'll work? If there are some special steps involved, can you document them in the readme?

Also, make sure to look at the comment I made. Otherwise, looks good. 👍Remember to squash and merge.

2018-04-18 04:29 UTC, churichard commented on webpack-stats.dev.json
> +{"status":"done","publicPath":"http://localhost:3000/","chunks":{"main":[{"name":"static/js/bundle.js","publicPath":"http://localhost:3000/static/js/bundle.js","path":"C:\\Users\\Daniel\\Desktop\\Cla
If this is autogenerated, I think you can leave it out, right?

2018-04-18 05:18 UTC, danielleung27 commented on webpack-stats.dev.json
> +{"status":"done","publicPath":"http://localhost:3000/","chunks":{"main":[{"name":"static/js/bundle.js","publicPath":"http://localhost:3000/static/js/bundle.js","path":"C:\\Users\\Daniel\\Desktop\\Cla
Yeah I'll leave it out. For development, you have to go to the folder "frontend" and run 'npm start'. Then you can run the django server and it'll work. For production you do something where the react thing will run from just starting the django server but I wasn't able to test that out because our production settings weren't working yet.

2018-04-18 05:22 UTC, merged