Req popovers
TigerAppsOrg/TigerPath pull request #121
Opened 2018-07-22 00:49 UTC by danielleung27

2018-08-10 06:53 UTC, bnehoran commented
I've played around with it a bit, and it looks like it's going in the right direction.
I still need to go through the code more thoroughly, since I haven't done that, but just from playing with it, I've noticed that the popovers for the courses now sometimes appear in the wrong place. Do you know why that happens?

Here's an example: 
![image](https://user-images.githubusercontent.com/9757500/43942948-e3762d0a-9c47-11e8-8297-5ca9ff66ad79.png)

It seems like its always for courses in the rightmost column.

2018-08-10 07:04 UTC, bnehoran commented
It's also somewhat difficult to "catch" the req popovers, since when I start moving my mouse in the direction of the popover, the moment I move off of the box in the req tree, the popover I was trying to catch disappears. The only way is to move really fast to get there before it disappears.

2018-08-10 07:16 UTC, danielleung27 commented
The popup appearing in the wrong place should be an easy fix. Its because of my styling on left popovers that I did to fix the req popovers. For the issue about it being hard to catch, would it help if the popover was closer to the req tree? I can move it closer if it helps

2018-09-03 19:11 UTC, churichard requested changes
Haven't looked at the code yet, but a couple of points:

- It looks like you're using the explanation from one level higher than you should be.
- Long explanation text in a requirement near the top of the page gets cut off the page.
- You're showing the contacts and urls when you hover over the major/degree. Is that something we want to do? The urls in particular look a bit not user friendly.

2018-09-04 19:17 UTC, danielleung27 commented
Yeah I can't really figure out how to prevent the long text from getting cut from the top. Popover positioning is really hard, the popover seems to be placed above or below the arrow at random points, I also had to use a css to offset the popovers to the left, its default placement covers the requirements. For the contacts and urls, where else would we put them?

2018-09-09 04:13 UTC, bnehoran requested changes
- As Richard said, the explanations are being pulled from the parent of the requirement rather than the requirement itself. (Note that by contrast, the titles _are_ coming from the correct requirement. Only the explanation isn't.) That definitely needs to be fixed before approval. (**critical**)

- The popover for the major should include the major's explanation field, if it exists (in addition to the currently included info).

- The `\n` character should be treated appropriately as a newline to get the proper formatting for the explanations. Right now, they're all clumped up into a single paragraph, which is really hard to read.

- The text inside the search button "Search Requirement" doesn't seem clear enough about what it actually does. (Does it search Google? the registrar's office? What kind of search?) Maybe something more like "Search for courses" or "Find courses" or "Search by this requirement", or something else that makes it more clear. Not sure what the best help text would, but something similar that's clear what it does as well as concise.

- I actually like that the contacts are shown, though I'd like the emails to be made into email links (though not super important). In regards to the links, I'm not sure. Maybe at the very least, they should have a heading "Relevant links", and each link's text should be cut off with an ellipsis (...) to fit on one line. Probably not as important as the other issues, though.

2018-09-09 04:17 UTC, churichard commented
Perhaps "Find satisfying courses" would be good for the button

2018-09-09 08:55 UTC, bnehoran commented
Apparently, long explanations near the bottom also get cut off:

![image](https://user-images.githubusercontent.com/9757500/45262803-30f7cc80-b3ec-11e8-81ca-f1c4d8303ece.png)

I think it's just going in the wrong direction. If it's in the lower part of the screen, it should be going up, and if it's in the upper part of the screen, it should be going down.

2018-09-11 00:50 UTC, bnehoran commented
Wow, that looks much better!

Two remaining issues for me:
- The popovers are still really difficult to catch. I think they've moved even farther away than they were before (!) Should be an easy fix, right? 
- The overflow outside the screen is still annoying. If we can't fix it and it comes down to just that, I think it's not the end of the world (we can issue a fix later), but it would be great if this could be fixed.

In my opinion, the other things, we could live with and come back to them after launch.

2018-09-11 02:21 UTC, bnehoran commented
Popover placement is inconsistent across different size screens:
![image](https://user-images.githubusercontent.com/9757500/45334199-c52a7680-b547-11e8-9166-5e0ef84b892d.png)
![image](https://user-images.githubusercontent.com/9757500/45334206-cd82b180-b547-11e8-82f5-0d0f28004b36.png)

2018-09-12 04:26 UTC, churichard commented on frontend/src/Search.js
> +                                  reqpath={mainReq['path_to']}
What's this used for?

2018-09-12 05:18 UTC, bnehoran commented on frontend/src/Search.js
> +                                  reqpath={mainReq['path_to']}
It's not used.

2018-09-12 05:21 UTC, bnehoran approved these changes

2018-09-12 05:58 UTC, churichard approved these changes

2018-09-12 06:07 UTC, merged