Integrate frontend with backend, added drag/drop
TigerAppsOrg/TigerPath pull request #13
Opened 2018-04-20 07:02 UTC by danielleung27

Integrated search engine with frontend, added drag drop feature, added api for post request for updating schedule in backend.

Courses.js is not needed anymore but keeping the file just in case. Will probably delete soon.

2018-04-20 16:31 UTC, churichard requested changes
Looks neat! I added a few comments.

There are some things that need to be addressed in order for this to be fully usable (but doesn't have to be in this pull request):

- Need to add a scrollbar for the course searching
- Need to protect the api endpoints somehow (right now anyone can access them, which is a problem) (may need to use tastypie)
    - Also need to remove CSRF exempt (may need to follow these steps: https://docs.djangoproject.com/en/2.0/ref/csrf/#acquiring-the-token-if-csrf-use-sessions-is-false)
- Allow adding the same course multiple times (which is the current behavior), but show a tooltip saying that the course is a duplicate if it already exists in the schedule. There are some courses (like CWR 202) which you can take multiple times.
- Add "X" button to remove courses from a semester
- Add course name to each card in the search results
- Add a django-admin command to combine semester data from past four years into one comprehensive course list (with typical times that the course is offered, etc.)
- Prevent users from moving a course in their schedule back to the course search
- Prevent users from reordering courses in the course search

2018-04-20 16:31 UTC, churichard commented on frontend/src/Search.js
> +      let courses_taken = [[],[],[],[],[],[],[],[]];
Instead of hardcoding the semester here, you can make `courses_taken = []` and then under `added_courses.forEach(function (semester){` you can put `courses_taken.push([])`

2018-04-20 16:31 UTC, churichard commented on frontend/.gitignore
> +package-lock.json
Remove these three lines (I added them before but they're actually not necessary)

2018-04-20 16:31 UTC, churichard commented on frontend/src/Courses.css
> +.gu-mirror {
I think most of these gu classes/properties are from dragula, right? A cleaner way to import them might be to do `import styles from 'dragula/dist/dragula.css';` in Courses.js and Search.js (according to https://github.com/bevacqua/react-dragula/issues/27) and then only specify the specific properties you want to add/override in Courses.css.

2018-04-20 16:31 UTC, churichard commented on frontend/src/Search.js
>  import jQuery from 'jquery'
Don't think you need to import `jQuery` if you're already importing `$`

2018-04-20 16:31 UTC, churichard commented on tigerpath/templates/tigerpath/index.html
> +              <td id="sem1" class="course">  </td>
I don't think it makes sense for the css class of a semester to be `course`. Change this to `semester` and change the class in the css file to `semester` as well

If you change the draggable logic, then you can probably get rid of the ids as well

2018-04-20 16:31 UTC, churichard commented on frontend/src/Search.js
> +    let drake = dragula([document.getElementById("display_courses"),
If you wanted this to be cleaner, you can do something like this with jquery:
```javascript
let draggableItems = $(".semester").get()
draggableItems.append($("#display_courses")[0])
let drake = dragula(draggableItems)
```
This assumes that you changed the css class to `semester`.

2018-04-20 16:31 UTC, churichard commented on frontend/src/Search.js
> +      console.info(courses_taken);
Remove this

2018-04-20 16:31 UTC, churichard commented on frontend/src/Courses.js
> +    let drake = dragula([document.getElementById("course_list"),
Can change this logic to the modified logic in Search.js

2018-04-20 16:31 UTC, churichard commented on tigerpath/templates/tigerpath/index.html
>      </script>
I can't quite comment on the correct line, but you're not using this draggable bundle, right? I think you can get rid of the line `<!-- draggable bundle -->` and the one below it

2018-04-20 16:31 UTC, churichard commented on tigerpath/views.py
> +@csrf_exempt
Does this actually need to be `csrf_exempt`?

2018-04-20 16:51 UTC, churichard commented on tigerpath/urls.py
>      path('api/v1/get_courses/<search_query>', views.get_courses, name='get_courses'),
Also, add a comment above this line: `# api`

2018-04-21 19:58 UTC, churichard requested changes

2018-04-21 19:58 UTC, churichard commented on frontend/src/Search.js
> +            $("#" + course["id"]).off("click").click(function(){
Courses should not be removed by simply clicking on them anywhere - this makes it way too easy to accidentally remove courses. You should have an explicit `X` button on the right side that will remove a course when clicked

Also, doesn't make much sense to have this onclick listener in this function. It should be separated out and only added once (that way you won't need to have the `.off("click")` call)

2018-04-21 19:58 UTC, churichard commented on frontend/src/Search.js
> +                $("#display_courses").append($(this)[0].outerHTML);
Don't add the course back to the course listings. Doesn't make much sense to do that

2018-04-21 19:58 UTC, churichard commented on frontend/src/Search.js
> +    let get_courses = function(){
JavaScript uses camelCase as the convention for variable names and function names.

Also, this is not the most descriptive function name. A better one might be `updateSchedule` (since that's what you're doing). The get courses logic might also be able to be separated out into another function

2018-04-21 22:20 UTC, danielleung27 commented on frontend/src/Search.js
> +            $("#" + course["id"]).off("click").click(function(){
I put the onclick listener in the updateSchedule function so that only the courses in the schedule can be deleted (and not the ones in the search). Once I add the X's on the courses I think I can make this cleaner by selecting all X elements.

2018-04-21 22:22 UTC, danielleung27 commented on frontend/src/Search.js
> +                $("#display_courses").append($(this)[0].outerHTML);
I was thinking if a user searches Cos and adds a couple classes and then removes some, the removed Cos courses should go back to the search list. It might be weird if they have Ele searched and then they remove a cos class and it goes to the search, but I don't think it is as annoying as if they were to search Cos, add 3 classes, remove one, and then have to re-search Cos if they want to re-add the one they removed.

2018-04-21 23:30 UTC, churichard commented on frontend/src/Search.js
> +                $("#display_courses").append($(this)[0].outerHTML);
In that case, I think it might be best to have it so that every time the user removes a course, it checks to see if it should be in the search results and if so, it adds it back in in the correct sorted order. However, if the course wouldn't be in the search results anyway, then it shouldn't add it back in. This is similar to the behavior that Recal has

2018-04-21 23:31 UTC, churichard commented on frontend/src/Search.js
> +            $("#" + course["id"]).off("click").click(function(){
It might be cleaner to add a css class or something to a course when it's dragged and dropped into the schedule. Then you can just select for that css class

2018-04-21 23:36 UTC, danielleung27 commented on frontend/src/Search.js
> +            $("#" + course["id"]).off("click").click(function(){
I'm not sure if it's possible to get the element that had just been dropped using the Dragula library so that's why I have the onclick listener in the update schedule function since that function loops through each course on the schedule. Whenever a course is added it loops through all courses again so I had to do the .off('click') thing so a listener isnt added twice on a course.

2018-04-21 23:42 UTC, churichard commented on frontend/src/Search.js
> +            $("#" + course["id"]).off("click").click(function(){
Try the `drop` event: https://github.com/bevacqua/dragula#drakeon-events

2018-04-21 23:51 UTC, churichard commented on tigerpath/views.py
> +@csrf_exempt
P.S. I think you can remove this annotation if you add a csrf token to your request. You can try looking here to see how to do it: https://docs.djangoproject.com/en/2.0/ref/csrf/#acquiring-the-token-if-csrf-use-sessions-is-false

2018-04-22 02:42 UTC, danielleung27 commented on frontend/src/Search.js
> +                $("#display_courses").append($(this)[0].outerHTML);
I'm trying to get the relative ordering back by accessing this.state.data which gives the list of the courses in the search. I think the way React works is that when assigning listeners you have to bind the context of this to the listener so whenever I bind delete onto a button, it only has access to the data at the moment that it was binded. So if I add a cos class, this.state.data will be the list of cos classes and i can only access this list in the listener. If I search ELE and add an ele course, the cos class can't access the current state's data. So I might have to reassign all the listeners whenever a drop event occurs.

2018-04-23 02:04 UTC, churichard requested changes
A few extra things that should be fixed (for reference) (this list supersedes the above list):
- Fix the extra white space that appears after a long course search
- Need to protect the api endpoints somehow (right now anyone can access them, which is a problem)
- Add a django-admin command to combine semester data from past four years into one comprehensive course list (with typical times that the course is offered, typical semester, etc.)

2018-04-23 02:04 UTC, churichard commented on frontend/src/Courses.css
> +    /* Position the tooltip text - see examples below! */
remove comment

2018-04-23 02:04 UTC, churichard commented on frontend/src/Courses.css
> +  border-bottom: #ddd;
remove comments

2018-04-23 02:04 UTC, churichard commented on frontend/src/Search.js
> +      copy: function(el, source){return el.parentElement.id == "display_courses";},
Use `===` instead of `==` everywhere

2018-04-23 02:04 UTC, churichard commented on frontend/src/Search.js
> +      if($('[id=' + course.id +']').length > 3){
`$('[id=' + course.id +']'` can be a variable

2018-04-23 02:04 UTC, churichard commented on frontend/src/Search.js
> +        $(".delete_course").click(function(){
Is it possible to change the id of a copied course? Might be rather expensive to keep assigning event listeners on every drop event (especially since you're not removing previous ones that have been assigned to the same object)

2018-04-23 02:04 UTC, churichard commented on frontend/src/Search.js
> +              <span className="tooltiptext-custom">Note: class already added</span>
I think this tooltip should only be added to classes that are actually duplicates, not to every class. We may want to add extra tooltips in the future to notify the user of stuff other than duplicate classes

2018-04-23 02:04 UTC, churichard commented on frontend/src/Search.js
> +    function removeParent(){this.parentNode.remove();}
What does this do?

2018-04-23 02:04 UTC, churichard commented on frontend/src/Search.js
> +              <span className="course_name">{course["listing"]}</span><span className='delete_course'>✖</span><br />
Minor thing, but I think this delete course button should only appear when a course is added to the schedule

2018-04-23 03:58 UTC, danielleung27 commented on frontend/src/Search.js
> +              <span className="course_name">{course["listing"]}</span><span className='delete_course'>✖</span><br />
It might be a little annoying to do since tooltip should be the last element and I would have to insert the delete element in a specific location rather than using append.

2018-04-23 04:13 UTC, churichard approved these changes

2018-04-23 04:13 UTC, churichard commented on frontend/src/Search.js
> +              <span className="course_name">{course["listing"]}</span><span className='delete_course'>✖</span><br />
Better way to do this would be to have some css that positions the delete button instead of having the position be determined by the html. A bit more work but would make styling the courses more flexible

2018-04-23 04:26 UTC, merged