Add ORF major
TigerAppsOrg/TigerPath pull request #134
Opened 2018-08-26 19:39 UTC by danielleung27

2018-08-27 12:09 UTC, bnehoran commented
Addresses #128

2018-09-02 06:17 UTC, bnehoran requested changes
* Some extra fields (empty req and course lists, `completed_by_semester`, `allowed_majors`, `double_counting_allowed`) should be removed to conform to schema.
* Should to be tested with frontend to ensure proper functionally (not clear if this has been done)
* At least one test should be written in `verifier_tests` (to ensure that future changes in verifier don't break this major's functionally)
* I haven't reviewed the content very thoroughly against the departmental page, so that needs to be done as well.

2018-09-02 06:17 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/ORF_2018.json
> +    "year": 2018,
Needs "degree" field

2018-09-02 06:17 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/ORF_2018.json
> +    "allowed_majors": [],
Remove
This is only for certificates.

2018-09-02 06:17 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/ORF_2018.json
> +            "completed_by_semester": 8,
`double_counting_allowed` is false by default, and `completed_by_semester` is 8 by default, so no need to include explicitly. They don't hurt necessarily, but I've been adding them only when they're not the default values, so that it's less cluttered.
We might want to decide on a standard (whether to be explicit or implicit with these).

2018-09-02 06:17 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/ORF_2018.json
> +            "req_list": [],
Remove this. The interpreter assumes only a `req_list` *or* a `course_list` exists, so it does not get interpreted properly if they both appear.
Yes, the form spits them both out (sorry about that, but I couldn't find a way around it), so unfortunately, the empty one just has to be removed afterwords (easy with find and replace).

2018-09-02 06:17 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/ORF_2018.json
> +                        "ORF 311",
Are these all the upper level courses in the ORF department?
If it is, they can be specified by 
`ORF 3**` and `ORF 4**`
It's easier to read/debug and more maintainable in case the courses available change.
If not (or if some courses are left out) then this is okay for now. In the future, we should add an ability to exclude courses as mentioned in #100

2018-09-02 06:17 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/ORF_2018.json
> +                    "max_counted": 10,
No need for this `max_counted` since it's enforced by the parent, right?

2018-09-02 06:17 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/ORF_2018.json
> +            "req_list": [],
Also in multiple other places.

2018-09-02 06:17 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/ORF_2018.json
> +            "completed_by_semester": 8,
Also appears in multiple other places

2018-09-02 06:17 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/ORF_2018.json
> +            "explanation": "A full-year thesis (or a one semester project plus an additional 400-level ORFE departmental) involving an application of the techniques in the program applied to a topic
From the description, it seems like there are two options for this requirement?

It looks like only only one is listed.

2018-09-02 19:56 UTC, danielleung27 commented on tigerpath/majors_and_certificates/majors/ORF_2018.json
> +                        "ORF 311",
There was a list provided, it might not be all the upper level departmentals for orf.

2018-09-09 21:21 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/ORF_2018.json
> +                        "ORF 311",
If it's from an explicit list, then that's fine. Best to have it the same way they specify it.

2018-09-12 07:18 UTC, bnehoran approved these changes

2018-09-12 07:19 UTC, bnehoran commented
Still need to add test cases in `verifier_tests`, but this can be done later.

2018-09-12 07:19 UTC, merged