Add CEE major
TigerAppsOrg/TigerPath pull request #135
Opened 2018-08-26 22:56 UTC by danielleung27

Add CEE major

2018-08-27 12:08 UTC, bnehoran commented
Addresses #129

2018-09-02 06:26 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CEE_2018.json.txt
> +            "name": "Branko Gli�ic",
Do we support characters with diacritics? How well do the display in the frontend?

2018-09-02 16:57 UTC, bnehoran requested changes
See comments for similar issues in #134

2018-09-02 16:57 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CEE_2018.json.txt
> +{
Should have a .json extension.

2018-09-02 18:10 UTC, bnehoran commented
Addressed some of the format issues so that it can be viewed/used inside the app to more easily test it and check the content.

Still needs to be tested and reviewed for content/correctness as mentioned in https://github.com/TigerPathApp/tigerpath/pull/134#pullrequestreview-151609789

2018-09-07 17:59 UTC, bnehoran requested changes
Still need to allow double-counting across tracks.

Also, should consider factoring out requirements that are common across all tracks.
This would make it easier for users to navigate, as well as for us to maintain.

2018-09-07 20:24 UTC, danielleung27 commented
Why should double counting be allowed across tracks? Students can only do 1 track I think? Also factoring out the requirements might be a little confusing. The CEE website separates the 5 tracks with requirement lists without factoring out common courses so a user familiar with how it is structured on the website will get confused here.

2018-09-09 06:52 UTC, bnehoran approved these changes
I've gone through the content and compared it to the official requirements pages.
I also did a bit of testing within the app, but it's difficult to do at the moment because there are so few semesters of courses, that many of the courses required for the major don't exist. So more testing should be done at some point to check that all the requirements can indeed be fulfilled within the app.

I fixed any problems I found as I discovered them. Most seem to be due to confusion from the inconsistencies between different sources (for instance, additional math and science requirements only appear in the CEE "Yello Book").
The requirements for the "Engineering and the Liberal Arts" track still look suspect, but it's unclear from the undergraduate announcement or from the department web page what the requirements actually are.
In both cases, we need to verify with someone who is more familiar with the major.

Lastly, still no test cases in `verifier_tests`, but I think this is okay for now. We can add some later.

2018-09-09 06:58 UTC, merged