Search text changed on search by req
TigerAppsOrg/TigerPath pull request #146
Opened 2018-09-04 23:02 UTC by adeniji19

I think the best choice is to put generic text so the user knows what is being displayed but doesn't think they can replicate by typing it into the search bar.

2018-09-06 23:20 UTC, churichard requested changes
I think displaying the requirement title would be more informative, since the user might forget what was searched.

2018-09-09 08:03 UTC, bnehoran commented
I removed the commits that were unrelated to this pull request, so if your local branch still has those commits but you want to pull, you just have to do `git reset --hard master` before doing `git pull`.

----------------------------
Caveat: If you have local, unpushed commits you want to keep, you might want to first make a copy of the branch. For instance,
```bash
git branch old_search_text
git reset --hard master
git pull
git cherry-pick old_search_text~[n]..old_search_text #replace the [n] with the number of commits to keep
```

2018-09-09 08:25 UTC, bnehoran commented
I removed the commits that were unrelated to this pull request and force pushed, so if your local branch still has those commits but you want to pull, you just have to do `git reset --hard master` before doing `git pull`.

----------------------------
Caveat: If you have local, unpushed commits you want to keep, you might want to first make a copy of the local branch. For instance,
```bash
git branch old_search_text
git reset --hard master
git pull
git cherry-pick old_search_text~[n]..old_search_text #replace the [n] with the number of commits to keep
```

2018-09-09 08:26 UTC, bnehoran approved these changes

2018-09-09 08:32 UTC, bnehoran commented
Resolves: #125

2018-09-09 19:15 UTC, churichard requested changes

2018-09-09 19:15 UTC, churichard commented on frontend/src/Requirements.js
> +  var filterText = 'Satisfying: ' + req_path.substring(req_path.lastIndexOf("//")+2,req_path.length);
A cleaner way to do this is by doing `req_path.split('//').pop()`

2018-09-09 19:15 UTC, churichard commented on frontend/src/Search.js
> +          name="search-text"
Don't use `name`, that's only used in forms. If you want to identify an element, use the field `id`

2018-09-09 19:15 UTC, churichard commented on frontend/src/Requirements.js
> +  document.getElementsByName('search-text')[0].value=filterText;
jQuery can do this more cleanly: `$('#search-text').val(filterText);`

2018-09-10 01:25 UTC, churichard requested changes

2018-09-10 01:25 UTC, churichard commented on frontend/src/Search.js
> +          input id="search-text"
Don't need `input` here, just `id` is fine.

2018-09-10 03:51 UTC, churichard approved these changes

2018-09-10 03:57 UTC, merged