Fixed tooltip and whitespace bugs
TigerAppsOrg/TigerPath pull request #18
Opened 2018-04-23 05:59 UTC by danielleung27

tooltip logic makes more sense now ( > 1 item triggers tooltip)

2018-04-23 15:45 UTC, churichard requested changes
When you hover over the course in the search list, the tooltip is cut off. I think this happens at certain widths. Can you fix that?
<img width="384" alt="image 2018-04-23 at 11 40 08 am" src="https://user-images.githubusercontent.com/4218237/39137297-3da77c32-46eb-11e8-9b81-1ac3590f77f5.png">

Might be easier to work with tooltips if you use [Bootstrap's tooltip component](https://getbootstrap.com/docs/4.0/components/tooltips/) instead of making it manually.

2018-04-23 15:45 UTC, churichard commented on frontend/src/Search.js
> +        search_list_course.find(".tooltiptext-custom").append("Note: class already added");
I think you might be able to chain this call after `.empty()`

2018-04-23 15:45 UTC, churichard commented on frontend/src/Search.js
>            $(this).find(".tooltiptext-custom").append("Note: class already added");
I think you might be able to chain this call after `.empty()`

2018-04-23 18:38 UTC, danielleung27 commented
I fixed the tooltips using the old tooltips but ignore it for now, I'm working on the bootstrap tooltip.

2018-04-23 21:20 UTC, churichard requested changes

2018-04-23 21:20 UTC, churichard commented on frontend/src/Search.js
> +      let search_list_course = $('#display_courses').find('[id=' + course.id +']');
Forgot to mention this earlier, but css classes should use dashes to separate words (so this should be `display-courses`)

2018-04-24 02:16 UTC, churichard approved these changes

2018-04-24 02:41 UTC, merged