Add POL
TigerAppsOrg/TigerPath pull request #185
Opened 2019-01-29 22:40 UTC by danielleung27

Add pol major

2019-01-30 07:56 UTC, bnehoran requested changes

2019-01-30 07:56 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/POL_2018.json
> +      "completed_by_semester": 8
```suggestion
      "completed_by_semester": 8,
      "no_req": null
```

2019-01-30 07:56 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/POL_2018.json
> +      "completed_by_semester": 6
```suggestion
      "completed_by_semester": 6,
      "no_req": null
```

2019-01-30 07:56 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/POL_2018.json
> +      "max_counted": 1,
```suggestion
      "max_counted": null,
```

2019-01-30 07:56 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/POL_2018.json
> +      "min_needed": 1,
```suggestion
      "min_needed": null,
```

2019-01-30 07:56 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/POL_2018.json
> +      "min_needed": 0,
```suggestion
      "min_needed": null,
```

2019-01-30 07:56 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/POL_2018.json
> +      "explanation": "During the senior year, each student writes a thesis. The senior thesis (link is external) normally is written on a topic within a student's primary field. The department encour
```suggestion
      "explanation": "During the senior year, each student writes a thesis. The senior thesis normally is written on a topic within a student's primary field. The department encourages students to use the summer between junior and senior year for work on the senior thesis.",
```

2019-01-30 07:56 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/POL_2018.json
> +      "explanation": "Students are required to complete two semesters of junior independent work (link is external). Junior Workshops will meet every other week of the Fall teaching period and on alt
Remove any appearances of `(link is external)`
```suggestion
      "explanation": "Students are required to complete two semesters of junior independent work. Junior Workshops will meet every other week of the Fall teaching period and on alternating weeks, students are required to view online plenary session video modules and attend a 50-minute discussion section. The plenary component provides common instruction in research procedures and techniques. In their Fall Junior Workshops, juniors will complete a series of assignments building up to a research prospectus. [NOTE: Junior Workshops are not considered courses and do not count toward satisfying departmental course requirements.] In the spring semester, juniors will complete a Junior Paper under the supervision of an independent work adviser. Students must achieve at least a “D” on each of their two semesters of junior independent work as well as an average of a “C” or above across the two. If the average of the two is below “C” or one of the two receives an “F”, a second Junior Paper is required (with a grade that brings the average of the Fall JIW and the Summer JP grades to at least a “C” or better). This is a prerequisite for beginning the senior year. For purposes of this requirement, the grades before the application of any late penalties are used.",
```

2019-01-30 07:56 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/POL_2018.json
> +      "min_needed": null,
Isn't at least one track required?
```suggestion
      "min_needed": 1,
```

2019-01-30 07:56 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/POL_2018.json
> +      "explanation": "The department maintains a list of politics courses that have an emphasis on methodological tools for research in political science. Concentrators are required to take a course
Remove `(link is external)`
```suggestion
      "explanation": "The department maintains a list of politics courses that have an emphasis on methodological tools for research in political science. Concentrators are required to take a course to fulfill the analytic requirement, normally no later than the first term of their junior year. The courses used to fulfill the analytic requirement cannot be used to fulfill primary-, secondary-, or third-field requirements. The analytic requirement may be satisfied by POL 341, POL 345/SOC 305, POL 346, or POL 347. We will also accept ANT 300A, ANT 301A, ECO 202, ECO 302, ECO 312, ORF 245, PHI 201, SOC 404, WWS 200, or WWS 332.",
```

2019-01-30 15:18 UTC, danielleung27 commented on tigerpath/majors_and_certificates/majors/POL_2018.json
> +      "min_needed": null,
I think they're optional. https://ua.princeton.edu/academic-units/department-department-politics#

2019-01-31 06:28 UTC, danielleung27 commented
Major is working and tested, after @194 is merged, it should work.

2019-02-02 05:53 UTC, bnehoran approved these changes

2019-02-02 05:53 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/POL_2018.json
> +      "min_needed": null,
I see

2019-02-02 06:11 UTC, merged