Modified data, schedule save/loading, search all semesters w/ color coding
TigerAppsOrg/TigerPath pull request #20
Opened 2018-04-25 08:35 UTC by danielleung27

Data has dist_area attribute now. Search now displays both semesters with color codes. Api endpoints protected, schedule saves in database and loaded when user logs in.

2018-04-25 22:15 UTC, churichard requested changes
Make sure to resolve the conflicts with `dev` as well

2018-04-25 22:15 UTC, churichard commented on tigerpath/management/commands/tigerpath_get_courses.py
> -        self.stdout.write('course selection: courses scraped successfully')
Might want to keep this line in just so we know the scraper has finished successfully

2018-04-25 22:15 UTC, churichard commented on tigerpath/views.py
>          query = query.upper()
You can probably just do `query.upper()` when you're checking the department

2018-04-25 22:15 UTC, churichard commented on tigerpath/views.py
> +    depts = set(['AAS', 'AFS', 'AMS', 'ANT', 'AOS', 'APC', 'ARA', 'ARC', 'ART', 'ASA', 'AST', 'ATL', 'BCS', 'CBE', 'CEE', 'CGS', 'CHI', 'CHM', 'CHV', 'CLA', 'CLG', 'COM', 'COS', 'CTL', 'CWR', 'CZE',
I actually think Recal's way of doing this (i.e. what you had before) is more maintainable, because you don't have to update the list of depts every time that changes (which, granted, won't be very often, but it still means that someone will have to remember to change this at some point). Like picking your battles, sometimes you have to pick your bugs, and this is probably a bug that no one will really notice (or if they do, it's minor and they won't care very much)

2018-04-25 22:15 UTC, churichard commented on tigerpath/views.py
> +# updates user's schedules with added courses
If you want to be more precise, `schedules` should probably be `schedule` (or `user's` should be `users'`)

2018-04-26 18:08 UTC, danielleung27 commented
The scraper is modified to maintain a master course list and I also modified the course models and scraper to have a field with the string of all of its crosslistings rather than doing database queries to convert from course model to course_listing model which speeds up the searching a lot. Searching for title is not slow anymore (old ajax calls are aborted when new ones are called now) but using abort() throws some errors in the server for some reason. I googled around and it says it might be a server issue so it might not happen on a different server? But searching is still fast but might be faster if this error was fixed.

2018-04-26 22:05 UTC, churichard requested changes
Another issue: tooltips don't show up when you reload the page.

Also, make sure to resolve conflicts with dev.

2018-04-26 22:05 UTC, churichard commented on frontend/src/Search.js
> +          if(current_request != null && current_request.readyState != 4) {
Comment this so readers know 4 means that the request is done

2018-04-26 22:05 UTC, churichard commented on tigerpath/scraper/scrape_all.py
> +     for term_code in term_codes:
this whole for loop should be one space unindented (i.e. what was here before)

2018-04-26 22:05 UTC, churichard commented on tigerpath/scraper/scrape_all.py
> +        if(course.is_master):
no parentheses in if statements in python

2018-04-26 22:05 UTC, churichard commented on tigerpath/scraper/scrape_all.py
> +                add_semester = "f" + course.registrar_id[1:3]
this is wrong - you should be subtracting the year by 1

2018-04-26 22:05 UTC, churichard commented on tigerpath/scraper/scrape_all.py
> +            # delete duplciate course
fix misspelling

2018-04-26 22:05 UTC, churichard commented on tigerpath/scraper/scrape_all.py
> +        # convert course to master model
indent

2018-04-26 22:05 UTC, churichard commented on tigerpath/scraper/scrape_all.py
> +            if(course.registrar_id[3] == '2'):
this is repeated code - combine it

2018-04-26 22:05 UTC, churichard commented on tigerpath/views.py
> +        course_info_list = sorted(course_info_list, key=lambda course: not (course['listing'].startswith(query.upper())))
I think you should also sort by number (100-level classes should appear before 200-level, etc), and it should be the number of the department that the user searched for. If the sorting is stable, you can probably just do it before this line

2018-04-26 22:05 UTC, churichard commented on tigerpath/views.py
> +        course_info_list = sorted(course_info_list, key=lambda course: not (course['title'].lower().startswith(query.lower())))
I don't think this is the most natural way to sort - I feel like we shouldn't really care about the placement of the searched word in the title. A better way would be to sort by dept name and code.

2018-04-26 22:05 UTC, churichard commented on tigerpath/views.py
> +def filter_courses(queries):
I think if you take advantage of queryset's lazy evaluation, this function could be even faster: https://docs.djangoproject.com/en/2.0/topics/db/optimization/#understand-querysets. So instead of filtering in Python, you could have the database filter and send back the filtered data

2018-04-26 22:05 UTC, churichard commented on tigerpath/views.py
> +        if(len(query.upper()) == 3 and query.upper().isalpha()):
no need to do query.upper() when you're calculating the length and whether or not it's alphabetic 😛

2018-04-26 22:05 UTC, churichard commented on tigerpath/models.py
> +    semesters = models.TextField(default="")
semesters should probably be an [array field](https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/fields/#arrayfield) instead of a string

2018-04-26 22:05 UTC, churichard commented on tigerpath/models.py
> +    cross_listings = models.TextField(default="")
cross_listings should probably be an [array field](https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/fields/#arrayfield) instead of a string

2018-04-26 22:05 UTC, churichard commented on tigerpath/views.py
> +            results = list(filter(lambda course: any([course_num.startswith(query) for course_num in re.split('\D+', course.cross_listings)]), results))
This doesn't handle `CEE 102A`

2018-04-27 05:29 UTC, churichard requested changes

2018-04-27 05:29 UTC, churichard commented on tigerpath/views.py
> +        if('f' in ''.join(course.all_semesters) and 's' in ''.join(course.all_semesters)):
You should only do the join once. Also, remove parentheses

2018-04-27 05:29 UTC, churichard commented on tigerpath/views.py
> +        elif('f' in ''.join(course.all_semesters)):
Remove parentheses

2018-04-27 05:29 UTC, churichard commented on tigerpath/views.py
> +        if(len(query) == 3 and query.isalpha()):
Remove parentheses

2018-04-27 05:29 UTC, churichard commented on tigerpath/views.py
> +        if(len(query) == 3 and query.isalpha()):
Remove parentheses

2018-04-27 05:29 UTC, churichard commented on tigerpath/views.py
>          elif(len(query) <= 3 and query.isdigit() or len(query) == 4 and query[:3].isdigit()):
Remove parentheses

2018-04-27 05:32 UTC, churichard approved these changes

2018-04-27 05:33 UTC, churichard commented
This pull request solves issue #17. Make sure to address the comments above and to resolve the conflicts.

2018-04-27 05:43 UTC, merged