Update landing page, navbar, supported majors, etc.
TigerAppsOrg/TigerPath pull request #232
Opened 2019-02-06 09:26 UTC by churichard

New landing page:

<img width="1440" alt="screen shot 2019-02-06 at 1 21 22 am" src="https://user-images.githubusercontent.com/4218237/52331632-87723280-29ad-11e9-8c1d-f94c8a504fe4.png">

2019-02-07 00:29 UTC, bnehoran commented on tigerpath/templates/tigerpath/about.html
> +        <p>Many students try to manually manage what courses they want to take and when they're taking them by using an Excel spreadsheet or pen-and-paper, but any mistake can easily lead to an overl
```suggestion
        <p>Many students try to manually manage what courses to take and when to take them by using an Excel spreadsheet or pen-and-paper, but any mistake can easily lead to an overloaded semester or a need to take summer classes in order to fulfill missed requirements.</p>
```

2019-02-07 00:33 UTC, bnehoran commented on tigerpath/templates/tigerpath/about.html
> +        <p class="majors-list"><li>Anthropology</li>
```suggestion
        <p class="majors-list">
          <li>Anthropology</li>
```

2019-02-07 22:42 UTC, bnehoran commented
I'm not sure I like this new all blue background.
What's wrong with the path image we have now?

2019-02-08 01:42 UTC, churichard commented
The background is actually a blue gradient that fades down, which looks a
little better than full blue. I'm open to alternatives on this, though.

I wanted to get rid of the image because it loads slowly and it doesn't
clearly inform potential users what our app is about when they first visit
our website. The new design presents them with the gif immediately and
gives them a better idea of what TigerPath is like.

On Thu, Feb 7, 2019, 3:07 PM bnehoran <notifications@github.com> wrote:

> I'm not sure I like this new all blue background.
> What's wrong with the path image we have now?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TigerPathApp/tigerpath/pull/232#issuecomment-461623336>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEBdfdEa6_aQRkcbe5wm8VQOuSJkLpM6ks5vLLG6gaJpZM4ak1Rs>
> .
>

2019-02-10 04:28 UTC, bnehoran requested changes
The home page looks good! I like the updated layout.

I sort of miss the grey navbar, and I also think it should appear on all the pages in order to be consistent with the main page (the page with the user schedule).
Also, the text on the About and Privacy pages is pretty hard to read, so that should be fixed.

2019-02-11 05:08 UTC, bnehoran approved these changes

2019-02-11 05:39 UTC, merged