cos req updates
TigerAppsOrg/TigerPath pull request #271
Opened 2019-09-24 11:13 UTC by Daniel-Wey

2019-09-26 22:05 UTC, bnehoran requested changes
Looking good! You can test out your changes on heroku by pressing the "View Deployment" button above or at the bottom under "Show Environments".

See my individual comments for specific feedback, but one additional thing: I think COS 511 is missing from Theory, isn't it?

2019-09-26 22:05 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/COS-AB_2018.json
> +          "explanation": "<i>Editor's Note: Beginning with the Class of 2023 CHM 301, ECO 312 and Physics courses will no longer count as COS departmentals.</i>\n\nAny computer science (COS) course a
```suggestion
          "explanation": "<i>Note: Beginning with the Class of 2023 CHM 301, ECO 312 and Physics courses will no longer count as COS departmentals.</i>\n\nAny computer science (COS) course at the 300 or 400 level (except independent work) counts as a computer science departmental.\nIn addition, any 300- or 400- level Math or ELE or Physics or ORF course that does not duplicate COS content, Philosophy 312, MAE 345, CHM 303(CHM 303 is now renumbered to CHM 301 as of 8/27/2018), ECO 312, MOL 437/NEU 437, NEU 330, MUS 315, and ECO 326 – Economics of the Internet count as departmentals.  On occasion, special courses with computational content from other departments may fall in to this category.",
```
Editor's note means more that you, the editor, are adding the note. In this case it comes from directly from the department.

2019-09-26 22:05 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/COS-BSE_2018.json
> +                "COS 401/TRA 301: Introduction to Machine Translation",
Good catch! (the extra space)
In reality the names here are just for reference (that is, everything after the colon is ignored), but good to keep it neat and consistent.

2019-09-26 22:05 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/COS-AB_2018.json
>                  "COS 401/TRA 301: Introduction to Machine Translation ",
```suggestion
                 "COS 401/TRA 301: Introduction to Machine Translation",
```
Just, if we're already fixing it in one, then we might as well fix it in the other.

2019-09-26 22:05 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/COS-BSE_2018.json
> +          "explanation": "<i>Editor's Note: Beginning with the Class of 2023 CHM 301, ECO 312 and Physics courses will no longer count as COS departmentals.</i>\n\nAny computer science (COS) course a
```suggestion
          "explanation": "<i>Note: Beginning with the Class of 2023 CHM 301, ECO 312 and Physics courses will no longer count as COS departmentals.</i>\n\nAny computer science (COS) course at the 300 or 400 level (except independent work) counts as a computer science departmental.\nIn addition, any 300- or 400- level Math or ELE or Physics or ORF course that does not duplicate COS content, Philosophy 312, MAE 345, CHM 303(CHM 303 is now renumbered to CHM 301 as of 8/27/2018), ECO 312, MOL 437/NEU 437, NEU 330, MUS 315, and ECO 326 – Economics of the Internet count as departmentals.  On occasion, special courses with computational content from other departments may fall in to this category.",
```
Same as in the AB version.

2019-09-26 22:18 UTC, bnehoran commented
Oh, also this is not too important, but it's customary to add a short description to the pull request summarizing the changes and/or why they were made. It helps a lot when looking back through the history.

2019-10-01 15:13 UTC, Daniel-Wey commented
> See my individual comments for specific feedback, but one additional thing: I think COS 511 is missing from Theory, isn't it?

COS 511 should now be added in the course list and explanation of theory courses.

2019-10-01 15:15 UTC, Daniel-Wey commented
> Oh, also this is not too important, but it's customary to add a short description to the pull request summarizing the changes and/or why they were made.
> You can also look at previous pull requests/commits for how to format the title of the PR.
> These are just nits, but they help a lot when looking back through the history.

Updated the description of the initial merge request

2019-10-07 12:43 UTC, Daniel-Wey commented on tigerpath/majors_and_certificates/majors/COS-BSE_2018.json
> +                "COS 401/TRA 301: Introduction to Machine Translation",
Understood!

2019-10-09 21:53 UTC, bnehoran approved these changes

2019-10-09 21:54 UTC, merged