Add course settling
TigerAppsOrg/TigerPath pull request #29
Opened 2018-05-04 16:26 UTC by bnehoran

2018-05-04 18:09 UTC, churichard requested changes
Make sure to also move the `majors-and-certificates` folder into the `tigerpath` folder

2018-05-04 18:09 UTC, churichard commented on majors-and-certificates/scripts/verifier.py
>  majors_location = "../majors/" # path to folder containing the major requirements JSONs
These should probably be in all caps

2018-05-04 18:09 UTC, churichard commented on majors-and-certificates/scripts/verifier.py
> +    req = copy.deepcopy(req)
What's the point of the deepcopy?

2018-05-04 18:09 UTC, churichard commented on majors-and-certificates/scripts/verifier.py
> +    if req["name"] == None:
If you wanted to be really pythonic, you can do `if not req["name"]` (this assumes name always exists in req)

2018-05-04 18:09 UTC, churichard commented on majors-and-certificates/scripts/university_info.py
> +LANG_DEPTS = {
You're only using LANG_DEPTS, right? I don't think you should have the other info here (makes it hard to maintain). TBH the LANG_DEPTS shouldn't be here either, it should be in the database.

2018-05-04 18:09 UTC, churichard commented on majors-and-certificates/scripts/verifier.py
> +                _add_course_lists_to_req(subreq, courses)
The `include_course_lists` variable is a bit janky, can you not just return right after this call?

2018-05-04 18:09 UTC, churichard commented on majors-and-certificates/scripts/tester.py
> +schema_location = "schema.json" # path to the requirements JSON schema
These variables should be all caps

2018-05-04 20:26 UTC, bnehoran commented on majors-and-certificates/scripts/verifier.py
> +    req = copy.deepcopy(req)
Because it's called as
a = f(b)
so it seems that the intuition would be that the function f doesn't modify b.

2018-05-04 21:25 UTC, bnehoran commented on majors-and-certificates/scripts/verifier.py
>  majors_location = "../majors/" # path to folder containing the major requirements JSONs
DONE

2018-05-04 21:27 UTC, bnehoran commented on majors-and-certificates/scripts/verifier.py
> +    if req["name"] == None:
Done

2018-05-04 21:29 UTC, bnehoran commented on majors-and-certificates/scripts/university_info.py
> +LANG_DEPTS = {
How do I do that without decreasing portability?

2018-05-04 21:33 UTC, bnehoran commented on majors-and-certificates/scripts/verifier.py
> +    if req["name"] == None:
Hmm... on second thought, it makes the code less clear:
Am I checking for a None value? an empty list? an empty string?

2018-05-04 21:37 UTC, bnehoran commented on majors-and-certificates/scripts/verifier.py
> +                _add_course_lists_to_req(subreq, courses)
No, because it still has to finish going through the other subrequirements.

2018-05-04 21:44 UTC, bnehoran commented on majors-and-certificates/scripts/tester.py
> +schema_location = "schema.json" # path to the requirements JSON schema
DONE

2018-05-05 03:26 UTC, churichard requested changes
Please also document the output of the verifier

2018-05-05 03:26 UTC, churichard commented on tigerpath/majors-and-certificates/scripts/tester.py
> +dir_path = os.path.dirname(os.path.realpath(__file__)) # the directory containing this file
This should probably also be in caps unless you're changing it somewhere

2018-05-05 03:26 UTC, churichard commented on tigerpath/majors-and-certificates/scripts/verifier.py
> +    return check_requirements(_get_dir_path(),degree_filepath, courses, year)
space after `_get_dir_path(),`

2018-05-05 03:26 UTC, churichard commented on tigerpath/majors-and-certificates/scripts/verifier.py
> +    semester number 'by_semester' (1-8)
Just checking, "by semester i" means "by the end of semester i", right? You may want to clarify this in the readme as well.

2018-05-05 03:26 UTC, churichard commented on tigerpath/majors-and-certificates/scripts/verifier.py
> +    for i,sem in enumerate(courses):
Why can't you just do:
```python
for i in range(by_semester):
   num_courses += len(courses[i])
return 1 if num_courses >= num_needed else 0
```
(not tested, adapt as you see fit)

2018-05-05 03:26 UTC, churichard commented on tigerpath/majors-and-certificates/scripts/verifier_tests/1.test.expected
> -      "used": true,
So if a course is not used, then `possible_reqs` is just empty, right?

2018-05-05 03:26 UTC, churichard commented on majors-and-certificates/scripts/university_info.py
> +LANG_DEPTS = {
Difficult to do. Maybe you can keep it as is for now.

2018-05-05 14:17 UTC, bnehoran commented on tigerpath/majors-and-certificates/scripts/tester.py
> +dir_path = os.path.dirname(os.path.realpath(__file__)) # the directory containing this file
DONE

2018-05-05 14:22 UTC, bnehoran commented on tigerpath/majors-and-certificates/scripts/verifier.py
> +    return check_requirements(_get_dir_path(),degree_filepath, courses, year)
This was a bug as well. The extra parameter only fits in os.path.join(), not in check_requirements, but I fixed it.

2018-05-05 14:23 UTC, bnehoran commented on tigerpath/majors-and-certificates/scripts/verifier.py
> +    semester number 'by_semester' (1-8)
Done

2018-05-05 14:29 UTC, bnehoran commented on tigerpath/majors-and-certificates/scripts/verifier.py
> +    for i,sem in enumerate(courses):
Done. Thanks!

2018-05-05 14:49 UTC, bnehoran commented on tigerpath/majors-and-certificates/scripts/verifier_tests/1.test.expected
> -      "used": true,
It depends on what you mean by "used".

If you want to know whether it was settled and used to actually satisfy a requirement, then look at the length of `reqs_satisfied` (>0 means it was used to satisfy at least one).

On the other hand, if `length(reqs_satisfied)` is 0, the length of `possible_reqs` says how many requirements it *could* be used to satisfy.
If both are 0, then it's really an unneeded course.

That's why I removed that field. It was simultaneously ambiguous and redundant.

2018-05-05 15:58 UTC, churichard approved these changes
Remember to also document the output json of the verifier

2018-05-05 16:00 UTC, merged