Display requirements pane
TigerAppsOrg/TigerPath pull request #31
Opened 2018-05-05 19:17 UTC by danielleung27

Added requirement tracker pane

2018-05-05 20:12 UTC, bnehoran submitted a review, later dismissed

2018-05-05 20:12 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +from .university_info import LANG_DEPTS
Are you sure about this change?

Adding this period in my code causes the tester code to generate the exception:

```
Traceback (most recent call last):
  File "scripts/tester.py", line 9, in <module>
    import verifier
  File "/home/ubuntu/workspace/tigerpath/majors-and-certificates/scripts/verifier.py", line 10, in <module>
    from .university_info import LANG_DEPTS
SystemError: Parent module '' not loaded, cannot perform relative import
```

2018-05-05 21:18 UTC, danielleung27 commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +from .university_info import LANG_DEPTS
When you run stuff in django, it works out. Individual files in django don't compile/run without errors. Django uses . for relative imports

2018-05-05 21:58 UTC, churichard requested changes
A couple of things:

- Move all of the requirements-specific logic outside of Search.js and into a new file
- I think the colors for the requirements pane should be changed - red should mean that a requirement is incomplete, and green should mean that a requirement is complete, and this should be true at all levels of the tree. You can use purple for the courses if you wish
- If you implement the above bullet point, then I think the color for fall semester should be changed as well (and perhaps also the color for fall/spring)
- Requirement headers should also have numbers at all levels (like 1/1)
- Why is degree progress not being checked?
- There's something a little funky with the humanities and social sciences section of the BSE requirements (only 2 is required, and some courses don't immediately settle even though they should). @bnehoran please check this.
- You've mentioned this already, but just to document it here: if a course is settled too quickly, then there are multiple copies of it
- There are some warnings in the console (in Chrome's developer tools) that I think are related to rendering the treeview, try to fix them
- Many of the requirements are 0/0 in Woody Woo. If min_needed is null maybe you should hide this number instead of displaying /0. This also underscores why we need to have numbers at all levels of the requirement headers

2018-05-05 21:58 UTC, churichard commented on frontend/src/Courses.css
> +  cursor: grab;
I think you might also want to change the cursor so that it is grabbing when the mouse is pressed. So something like this, maybe: 
```css
li:active {
  cursor: grabbing;
}
```

2018-05-05 21:58 UTC, churichard commented on tigerpath/static/app/css/app-style.css
> +  background-color: #fff4f4;
I don't think the red tint looks very good, can you remove it?

2018-05-05 21:58 UTC, churichard commented on frontend/src/Requirements.css
> +  background-color: #fff4f4;
I don't think the red tint looks very good. Maybe try another color. I also don't see what's wrong with white

2018-05-05 21:58 UTC, churichard commented on frontend/src/Search.js
> +        })
This should really be appended to the beginning of the next line, so that it'll look like `}));` in order to align it with the beginning of the block that's being closed

2018-05-05 21:58 UTC, churichard commented on frontend/src/Search.js
> +            if(requirement['settled'].length >= requirement['min_needed']) finished=' req_done';
Having the space in front of `req_done` is kind of janky, you may want to put the space after `tree-leaf-req` below instead (I assume that's what the space is for)

2018-05-05 21:58 UTC, churichard commented on frontend/src/Search.js
> +      let courseOnReq = $("#requirements").find("li:contains(\'" + course + "\')");
courseOnReq is never used, do you need this?

2018-05-05 21:58 UTC, churichard commented on frontend/src/Search.js
> +      let courseOnSchedule = $(".semesters").find("p:contains(\'" + course + "\')").parent();
You don't need the backslashes for the single quotes here

2018-05-05 21:58 UTC, churichard commented on frontend/src/Search.js
> +                    })
You forgot a semicolon

2018-05-05 21:58 UTC, churichard commented on frontend/src/Search.js
> +                      return mainReq[2]
What does `mainReq[2]` mean? Maybe you can add a comment here

2018-05-05 21:58 UTC, churichard commented on frontend/src/Search.js
> +          $.ajax({
This looks like repeated code. Refactor this out into only one place

2018-05-05 21:58 UTC, churichard commented on frontend/src/Search.js
> +
Superfluous blank line

2018-05-05 21:58 UTC, churichard commented on frontend/src/Search.js
> +        let pathListRemoved = courseOnSchedule.attr('reqs').split(',').splice(pathList.indexOf(path_to), 1).join()
This is just
```javascript
pathList.splice(pathList.indexOf(path_to), 1).join();
```

2018-05-05 21:58 UTC, churichard commented on frontend/src/Search.js
> +    let toggleSettle = function(course, path_to, settle){
This function (and the general way in which you're handling settling, especially in regards to the `reqs` attribute for the courses) is very confusing to me. Can you explain it?

2018-05-06 00:47 UTC, danielleung27 commented on frontend/src/Courses.css
> +  cursor: grab;
This makes the grabbing cursor only if you are move within the list item and turns into other cursors if you move outside. Leaving this here to fix later.

2018-05-06 00:52 UTC, danielleung27 commented on frontend/src/Search.js
> +        })
<img width="498" alt="screenshot_1" src="https://user-images.githubusercontent.com/22716583/39668777-26d30340-50a6-11e8-9b27-f1c8a91df0d0.png">
Does this look better?

2018-05-06 01:07 UTC, danielleung27 commented on frontend/src/Search.js
> +    let toggleSettle = function(course, path_to, settle){
Whenever a course is rendered on the requirements pane, it has a class 'settled' or 'unsettled text-muted' for styling settled and unsettled classes. A toggle settle function is also attached to these courses.

The courses that are displayed on the semesters is what is sent back through to the verifier so the toggleSettle function attaches more information to these elements so they are sent back as well so the backend (verifier) has access to it. The verifier takes in a list of paths (each requirement has a path for example: 'Computer Science - BSE // Core Courses // Theory') so it knows which requirement the course is supposed to satisfy. I attach these paths to the 'req' attribute of the courses on the schedule. The verifier reads this list and adds this course to each path requirement's 'settled' list. toggleSettle will remove the path and notify the verifier to update if the requirement being clicked on is already settled (the if statement handles this).

2018-05-06 04:26 UTC, churichard commented on frontend/src/Search.js
> +        })
I wasn't pointing to that part, I was looking below that. Line 95 closes line 70 from what I can tell, so it should be aligned with it. Something like this:
![fbf3faa9c5c31a0c27a03b41ed0b271e _image 202018-05-06 20at 2012 21 33 20am](https://user-images.githubusercontent.com/4218237/39669794-f4b7b7d4-50c3-11e8-9065-650d4ca19219.png)
In JavaScript it's just generally very easy to misalign curly braces and parentheses, which makes the code harder to read. It's important to make sure that things are aligned properly

2018-05-06 06:20 UTC, danielleung27 commented
I think I fixed everything except the bug where you settle a course multiple times and also for some reason the grabbing cursor stops grabbing when you move outside of the list item in the search.

Actually I may make another push, I might be able to implement the degree progress tracker.
update: done

2018-05-07 03:18 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +from .university_info import LANG_DEPTS
Well, if you're right, then isn't that a problem if the testing script cannot run?

2018-05-07 03:25 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +from .university_info import LANG_DEPTS
@danielleung27 @bnehoran  Try `scripts.university_info` instead?

2018-05-07 04:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +from .university_info import LANG_DEPTS
Okay @danielleung27 , you are right.

`from .university_info import LANG_DEPTS`
is the right way to do it since it's treating the scripts folder as a package.

The fix was just to move the tester.py file out of the package so that it can reference it, and do 
`from scripts import verifier`

I'll create a different pull request for that. No need for you to worry about it.

I approve then. Sorry about that.

2018-05-07 17:18 UTC, churichard commented
Before I look at this again, please update this branch with the latest changes in dev and resolve the conflicts

2018-05-07 20:21 UTC, churichard requested changes
- Should show the requirements even if the user_schedule is null (which means that the user is a new user with a blank schedule)
- If you take the same course twice, it should show up as unsettled twice in the requirements. Right now it shows up as unsettled once, and then when you settle it, it shows up as settled twice.

2018-05-07 20:21 UTC, churichard commented on frontend/src/Requirements.js
> +        let treeHash = requirement['name'].split("").reduce(function(a,b){a=((a<<5)-a)+b.charCodeAt(0);return a&a},0);
Please refactor all of this duplicate code

2018-05-07 20:21 UTC, churichard commented on frontend/src/Requirements.js
> +        if((requirement['min_needed'] == 0 && requirement['count'] >= requirement['max_counted']) ||
Please always use === instead of ==

2018-05-07 20:21 UTC, churichard commented on frontend/src/Search.js
> +            console.info(data)
Useful for debugging but shouldn't be in production

2018-05-07 20:39 UTC, bnehoran commented
@churichard the "only appearing as settled once" is actually my fault from the verifier. I had the verifier remove duplicates from the unsettled list, but I could fix that.

On the other hand, the problem with being settled twice is probably because the front end "settles" all the courses of the same kind (I don't know if determined by name, or ID, or what not) all at once.
So Daniel, see if you can fix that.

2018-05-08 05:23 UTC, churichard requested changes

2018-05-08 05:23 UTC, churichard commented on frontend/src/Requirements.js
> +    if($(this).attr('reqs').indexOf(path_to) === -1) courseOnScheduleNotAssigned = $(this);
Does this work if there are 3+ duplicate courses? Also, I get strange behavior where once I settle a course, another duplicate course shows up as unsettled right below it. I'm gonna say this is okay for now if you can't fix it, but it's something that needs to be fixed as part of issue #41

2018-05-08 05:23 UTC, churichard commented on frontend/src/Requirements.js
> +        let treeHash = getHash(requirement['name'])
It's not just this line but also the next 13 or so lines that are repeated between this if block and the next else block. Please refactor that out

2018-05-08 05:23 UTC, churichard commented on frontend/src/Search.js
> +      $.ajax({
Factor out this ajax call into another function, maybe `renderRequirements`

2018-05-08 05:23 UTC, churichard commented on frontend/src/Search.js
> +          updateSchedule();
Should call `renderRequirements` instead of `updateSchedule` after you make the change above

2018-05-08 05:28 UTC, bnehoran commented on frontend/src/Requirements.js
> +    if($(this).attr('reqs').indexOf(path_to) === -1) courseOnScheduleNotAssigned = $(this);
Does this happen regularly? Or only when you have duplicate courses?

2018-05-08 05:51 UTC, churichard commented on frontend/src/Requirements.js
> +    if($(this).attr('reqs').indexOf(path_to) === -1) courseOnScheduleNotAssigned = $(this);
Just for duplicate courses I believe

2018-05-08 05:51 UTC, churichard approved these changes

2018-05-08 05:53 UTC, merged