Prevent double-counting of language courses for BSE distribution requirements.
TigerAppsOrg/TigerPath pull request #361
Opened 2020-07-25 16:27 UTC by pranavavva

This is done by consolidating the multiple "hidden" subcategories into one "hidden" sub-requirement for Seven Total Courses.

Closes #359.

2020-07-25 16:35 UTC, pranavavva commented
We can merge this into master after merging my fork into this repo.

2020-07-25 18:54 UTC, bnehoran requested changes
This looks great, @pranavavva! Thanks for the pull request!

I just made two small comments about formatting, but once you've fixed that, I think it should be fine to merge it in!
Also, just so you know, I switched the base branch to `master`, since I think it should be okay to merge it in to `master` directly!

2020-07-25 18:54 UTC, bnehoran commented on tigerpath/majors_and_certificates/degrees/BSE_2018.json
> +              "dist_req": ["EC", "EM", "HA", "LA", "SA"],
Could you format this with one item per line (see the other lists in this file for reference)?

2020-07-25 18:54 UTC, bnehoran commented on tigerpath/majors_and_certificates/degrees/BSE_2018.json
> +                "LANG 5**"]
Just a small nit: the closing bracket should be on its own line (see the other lists in this file).

2020-07-25 19:01 UTC, bnehoran commented
Oh, also, just adding one more thing I noticed:
Since there is now only one subrequirement left of the children of "Seven Total Courses", then there's no reason to keep it as a subrequirement, so you can just move the `"dist_req"` and `"course_list"` fields up one level to its parent and then remove the `"req_list"` which is no longer needed.

2020-07-25 19:02 UTC, pranavavva commented
Thanks for the feedback! Will do...

2020-07-25 19:07 UTC, pranavavva commented
Alright, just pushed the new changes you requested. Please take a look and let me know what you think!!

2020-07-26 21:22 UTC, pranavavva commented
@bnehoran pinging you in case you didn't see my changes earlier.

2020-07-27 06:28 UTC, bnehoran approved these changes
Awesome, this looks great! Thanks @pranavavva!

I'm approving so that you can merge it in.

2020-07-27 16:42 UTC, pranavavva commented
@bnehoran It says I can't merge it because I don't have write access

2020-07-27 17:18 UTC, merged