Add dept reqs
TigerAppsOrg/TigerPath pull request #6
Opened 2018-03-27 23:20 UTC by bnehoran

Added json requirement files for AB, BSE, WWS, and COS (both AB and BSE), as well as additional helping files.

2018-04-01 04:11 UTC, churichard requested changes
Nice work! So far, I've only reviewed the AB and BSE requirements (which took a long time even by themselves).

What you should do:
- Get rid of the "scripts" folder and just have one folder named "dept_reqs"
- Remove everything except for the AB and BSE jsons from this pull request, and put them in separate pull requests separated out nicely, e.g. by major. You'll have to make separate branches for each pull request.
- Make the changes specified in my comments below

Please also document the JSON format (doesn't need to be in this pull request, you can do it in a different one), and submit smaller pull requests in the future.

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/AB_2018.json
> +  "url": "https://ua.princeton.edu/contents/program-study-degree-bachelor-arts",
Please put all the URLs where you gathered information from - this applies to all JSON files

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/AB_2018.json
> +      "min_needed": "",
The better style to represent values that don't exist in JSON is to write `null` (per [the official JSON website](http://www.json.org/)). Please change all the empty strings to `null` instead, both in this file and in all the other files.

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/AB_2018.json
> +      "name": "Writing Seminar",
Technically this needs to be done in freshman year, so you should put a `"completed_by_semester": 2`. Same with the BSE requirements

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/AB_2018.json
> +      "ReqList": [
Personally I think all json fields should be in snake_case (even nodes in the graph), so that there's no ambiguity to the programmer as to what kind of casing to use for each field. If you disagree, we can discuss further

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/AB_2018.json
> +        "WRI 1**"
How do you know this should be WRI 1**?

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/AB_2018.json
> +      "description": "",
Like the other requirements, this should also have a description

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/AB_2018.json
> +      "Req": "LANG"
Is the foreign language requirement (as well as the other distribution requirements) going to be done through code? Also, why is this `Req` and not `CourseList`?

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/AB_2018.json
> +  "Requirements": [
So does `Requirements` just mean that everything underneath it has to be satisfied, i.e. there is an implicit `min_needed` attribute in the root that is equivalent to the length of `Requirements`? Do you think it might be better to specify `min_needed`?

Also, what's the rationale behind having this be named `Requirements` and having the other `ReqList`s be named `ReqList`?

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/AB_2018.json
> +      "double_counting_allowed": false,
What does this `double_counting_allowed` field mean?

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/BSE_2018.json
> +      "CourseList": [
Remove this `CourseList` - doesn't seem like it should be here (plus it produces a syntax error because there's no comma afterwards)

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/AB_2018.json
> +  "courses_needed": 31,
Probably not needed - it's already encoded elsewhere. You can remove it from the BSE requirements too

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/AB_2018.json
> +  "note": "",
Do you use this `note` field at all? If not, I think it should be removed (both here and in other files) - it can always be added later if necessary

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/BSE_2018.json
> +          "NumCourses": 4
It seems to me like four courses is a general minimum course load for each semester, not just for the first semester. You should either encode this minimum for all semesters (as well as encode the minimum course load for each semester for the AB json), or delete it here in order to be consistent with how AB is currently formatted.

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/BSE_2018.json
> +      "description": "",
Like the other requirements, this should have a description

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/BSE_2018.json
> +            "MAT 216",
The requirements don't list MAT 216 as one of the possible courses to fulfill this

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/BSE_2018.json
> +          "explanation": "104 General Physics or 106 Advanced Physics, or equivalent",
Do we want to have some way to specify equivalent courses more precisely?

We can list the actual equivalent courses in the json, or we can just have some kind of signifier to say that there *are* equivalent courses, and then scrape them from the course offerings.

I think the second way is cleaner, but we'd have to be careful with how we get the equivalent courses. For example, ISC fulfills the chem requirements but is not listed as an equivalent course in CHM 201. However, CHM 201 is mentioned in the ISC course offerings page as one of the classes that ISC can count for (in the Other Information section, even - not in the Equivalent Courses section!)

If we do opt for the second option, we can have a ` - E` next to the course name to say that an equivalent course of it can be taken, or we can make each course name an object with various attributes instead of just a string

Perhaps the best solution would be to do the second option, but also put in courses like ISC into the json, since they're unique courses. What do you think?

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/BSE_2018.json
> +            "CHM 201A",
CHM 201A and CHM 203 aren't in the requirements list I'm looking at

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/BSE_2018.json
> +            "PHY 106"
I think ISC can fulfill the requirements for Physics as well

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/BSE_2018.json
> +            "COS 217",
Can COS 217 and COS 226 also fulfill this requirement?

2018-04-01 04:11 UTC, churichard commented on scripts/deptreqs/AB_2018.json
> +      "name": "Epistemology and Cognition",
Maybe you should make a `Req` for Distribution Requirements and then put all of the distribution requirements inside, in order to parallel how you do it for BSE

2018-04-04 23:25 UTC, bnehoran commented on scripts/deptreqs/AB_2018.json
> +  "url": "https://ua.princeton.edu/contents/program-study-degree-bachelor-arts",
Done

2018-04-04 23:25 UTC, bnehoran commented on scripts/deptreqs/AB_2018.json
> +      "min_needed": "",
Done

2018-04-09 22:55 UTC, bnehoran commented on scripts/deptreqs/AB_2018.json
> +      "name": "Writing Seminar",
done

2018-04-09 22:56 UTC, bnehoran commented on scripts/deptreqs/AB_2018.json
> +      "ReqList": [
Done

2018-04-09 22:57 UTC, bnehoran commented on scripts/deptreqs/AB_2018.json
> +        "WRI 1**"
https://writing.princeton.edu/seminars/fall-seminars

2018-04-09 22:58 UTC, bnehoran commented on scripts/deptreqs/AB_2018.json
> +        "WRI 1**"
Done

2018-04-09 23:01 UTC, bnehoran commented on scripts/deptreqs/AB_2018.json
> +      "Req": "LANG"
Yes. It is unfeasible to write out all the course combinations that could satisfy it.

2018-04-09 23:02 UTC, bnehoran commented on scripts/deptreqs/AB_2018.json
> +  "Requirements": [
Changed to req_list

2018-04-09 23:06 UTC, bnehoran commented on scripts/deptreqs/AB_2018.json
> +  "Requirements": [
Yes, the very top req_list has an implicit min_needed = "ALL"

2018-04-09 23:08 UTC, bnehoran commented on scripts/deptreqs/AB_2018.json
> +      "double_counting_allowed": false,
It indicates that courses in this subtree cannot be counted towards more than one branch.

2018-04-09 23:09 UTC, bnehoran commented on scripts/deptreqs/BSE_2018.json
> +      "CourseList": [
Done

2018-04-09 23:09 UTC, bnehoran commented on scripts/deptreqs/AB_2018.json
> +  "courses_needed": 31,
Done

2018-04-09 23:09 UTC, bnehoran commented on scripts/deptreqs/AB_2018.json
> +  "note": "",
Done

2018-04-09 23:11 UTC, bnehoran commented on scripts/deptreqs/BSE_2018.json
> +          "NumCourses": 4
Not sure how to encode this "courses per semester" within the existing format...

2018-04-09 23:38 UTC, bnehoran commented on scripts/deptreqs/BSE_2018.json
> +          "NumCourses": 4
Also, the AB course-load requirements seem to be a bit more complicated with senior thesis factoring in.

2018-04-09 23:39 UTC, bnehoran commented on scripts/deptreqs/BSE_2018.json
> +      "description": "",
Not sure what to put there.

2018-04-09 23:40 UTC, bnehoran commented on scripts/deptreqs/BSE_2018.json
> +      "description": "",
Also, I have a feeling that we might want to eliminate the "description" field and just merge it into the other two.

2018-04-09 23:41 UTC, bnehoran commented on scripts/deptreqs/BSE_2018.json
> +            "MAT 216",
from Degree Progress Report

2018-04-09 23:44 UTC, bnehoran commented on scripts/deptreqs/BSE_2018.json
> +          "explanation": "104 General Physics or 106 Advanced Physics, or equivalent",
Not sure. The second option seems complicated to implement, as I don't know how feasible it would be to automatically detect equivalent courses (as opposed to prerequisite courses etc.
I think we need to discuss this more in detail.

2018-04-09 23:45 UTC, bnehoran commented on scripts/deptreqs/BSE_2018.json
> +            "CHM 201A",
from Degree Progress Report

2018-04-09 23:45 UTC, bnehoran commented on scripts/deptreqs/BSE_2018.json
> +            "PHY 106"
Done

2018-04-09 23:47 UTC, bnehoran commented on scripts/deptreqs/BSE_2018.json
> +            "COS 217",
Apparently, according to the Degree Progress report

2018-04-09 23:51 UTC, bnehoran commented on scripts/deptreqs/AB_2018.json
> +      "name": "Epistemology and Cognition",
I think it's based on the way that they're listed on the respective requirements page. For BSE, for example, it's listed as a Humanities and Social Sciences requirement, whereas AB doesn't do that.
But maybe...

2018-04-11 23:25 UTC, churichard commented on scripts/deptreqs/BSE_2018.json
> +          "explanation": "104 General Physics or 106 Advanced Physics, or equivalent",
Okay, we'll keep it as is for now.

2018-04-11 23:26 UTC, churichard commented on scripts/deptreqs/AB_2018.json
> +      "name": "Epistemology and Cognition",
Let's stick with how it is for now then

2018-04-11 23:26 UTC, churichard approved these changes

2018-04-11 23:28 UTC, merged