Add collapsed course lists and additional info to verifier output
TigerAppsOrg/TigerPath pull request #71
Opened 2018-05-11 07:43 UTC by bnehoran

2018-05-12 22:49 UTC, churichard requested changes

2018-05-12 22:49 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +def _get_req_by_path(req, path_to):
Where is this supposed to be used? It's not a public function and isn't used anywhere in your code.

2018-05-12 22:49 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +            # course = "".join(course.split()).upper() # remove spaces
Remove this comment

2018-05-12 22:49 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +    Returns sets of all courses and of all distribution requirements
Say it's a tuple of (the set of all courses, the set of all distribution requirements)

2018-05-12 22:49 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +                total_course_set |= course_set
Might want to make a comment saying this is taking the union of both sets

2018-05-12 22:49 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +def _get_collapsed_course_and_dist_req_sets(req):
Do you think this might be better as a public function instead of integrated into check_requirements? This information is only relevant when the user wants to know what courses satisfy a requirement. It makes more sense to only return that information when necessary, instead of every time when the user settles a course.

2018-05-12 22:54 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +            # course = "".join(course.split()).upper() # remove spaces
Done

2018-05-12 22:55 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +    Returns sets of all courses and of all distribution requirements
Done

2018-05-12 22:56 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +                total_course_set |= course_set
I thought this should be clear / self evident.

It would be almost like writing
`i +=1 # increment the variable i`

2018-05-12 22:57 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +                total_course_set |= course_set
But okay, I added the comment

2018-05-13 00:12 UTC, churichard approved these changes

2018-05-13 00:15 UTC, merged