Get courses by path
TigerAppsOrg/TigerPath pull request #81
Opened 2018-05-13 08:58 UTC by bnehoran

Right now, the functions for getting the collapsed course sets are in the verifier since it was too much of a mess to try to move them out, and I want to make them available, so I will refactor it in the next iteration.

The `get_courses_by_path(path)` function returns a tuple with two sets. The first contains the courses and the second the distribution requirements for that requirement pointed to by `path`.

2018-05-15 20:32 UTC, churichard requested changes

2018-05-15 20:32 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +from .university_info import *
Don't use star imports. Instead, just import `.university_info` then write e.g. `university_info.LANG_DEPTS`

2018-05-15 20:32 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +        raise Exception("Major code not recognized.")
Raise a ValueError instead

2018-05-15 20:32 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +        raise Exception("Certificate not recognized.")
Raise a ValueError instead

2018-05-15 20:32 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
>  def check_requirements(req_file, courses, year):
Is check_requirements ever called by itself? If not, maybe you should put a _ in front of its name

2018-05-15 20:32 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +    return check_requirements(major_filepath, courses, int(year))
The year is not even used in check_requirements, why bother passing it in?

2018-05-15 20:32 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +        raise Exception("Year is invalid.")
Raise a ValueError instead

2018-05-15 20:32 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +    req_type, year, req_name = path.split('//')[:3]
I think it makes more sense for year to be the first parameter (since it changes yearly, but req_type and req_name are more static). What do you think?

2018-05-15 20:32 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +        raise Exception("Path malformatted.")
Raise a ValueError instead

2018-05-15 20:32 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +        raise Exception("Path malformatted.")
Raise a ValueError instead

2018-05-15 20:32 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +    elif  req_type == "Degree":
There's an extra space after "elif"

2018-05-15 20:32 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +        raise Exception("Path malformatted.")
Raise a ValueError instead

2018-05-15 20:32 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +        raise Exception("Path malformatted.")
Raise a ValueError instead

2018-05-15 20:32 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +                    if REQ_PATH_SEPARATOR + str(req["year"]) + REQ_PATH_SEPARATOR + req["code"] + REQ_PATH_SEPARATOR not in path:
Factor out `REQ_PATH_SEPARATOR + str(req["year"]) + REQ_PATH_SEPARATOR + req["code"] + REQ_PATH_SEPARATOR` into a variable (and it'll need to be changed if you switch the order of year and type)

2018-05-15 20:32 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +                    if REQ_PATH_SEPARATOR + str(req["year"]) + REQ_PATH_SEPARATOR + req["name"] + REQ_PATH_SEPARATOR not in path:
Factor out `REQ_PATH_SEPARATOR + str(req["year"]) + REQ_PATH_SEPARATOR + req["code"] + REQ_PATH_SEPARATOR` into a variable (and it'll need to be changed if you switch the order of year and type)

2018-05-15 20:32 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +    separator = REQ_PATH_SEPARATOR
Don't need separator, just use REQ_PATH_SEPARATOR

2018-05-15 20:32 UTC, churichard commented on tigerpath/majors_and_certificates/degrees/AB_2018.json
> +  "code": "AB",
If you're adding a code to the degree jsons, then make sure you update the readme as well

2018-05-16 22:29 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +from .university_info import *
Done

2018-05-16 22:34 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +        raise Exception("Major code not recognized.")
Done

2018-05-16 22:34 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +        raise Exception("Certificate not recognized.")
Done

2018-05-16 22:34 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +        raise Exception("Year is invalid.")
Done

2018-05-16 22:34 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +        raise Exception("Path malformatted.")
Done

2018-05-16 22:34 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +        raise Exception("Path malformatted.")
Done

2018-05-16 22:34 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +        raise Exception("Path malformatted.")
Done

2018-05-16 22:35 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +        raise Exception("Path malformatted.")
Done

2018-05-17 00:24 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
>  def check_requirements(req_file, courses, year):
Leaving public for now

2018-05-17 00:50 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +    return check_requirements(major_filepath, courses, int(year))
Removed

2018-05-17 00:50 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +    req_type, year, req_name = path.split('//')[:3]
Not sure

2018-05-17 01:08 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +    separator = REQ_PATH_SEPARATOR
Done

2018-05-17 01:18 UTC, bnehoran commented on tigerpath/majors_and_certificates/degrees/AB_2018.json
> +  "code": "AB",
Done

2018-05-17 01:18 UTC, bnehoran commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +    elif  req_type == "Degree":
Done

2018-05-17 03:24 UTC, churichard approved these changes
Make sure to make the change below

2018-05-17 03:24 UTC, churichard commented on tigerpath/majors_and_certificates/scripts/verifier.py
> +REQ_PATH_PREFIX = "%.12s" + REQ_PATH_SEPARATOR + "%d" + REQ_PATH_SEPARATOR + "%.100s"
Make sure to specify what the three parameters are in a comment

2018-05-17 06:38 UTC, merged