Master course updates info with latest course info
TigerAppsOrg/TigerPath pull request #82
Opened 2018-05-13 18:08 UTC by danielleung27

2018-05-13 18:25 UTC, churichard requested changes
So when the course number changes but the registrar id is the same, this doesn't do anything with the course number, right? I think it's fine for now, but we should think about what the best way to handle updated courses is

2018-05-13 18:25 UTC, churichard commented on tigerpath/scraper/scrape_all.py
> +            fetch_master.rating = course.rating
rating is not used, no need to update

2018-05-13 18:25 UTC, churichard commented on tigerpath/scraper/scrape_all.py
> +            fetch_master.dist_area = course.dist_area
I'm pretty sure dist_area shouldn't change. It's kind of problematic to update it like this because then one course might fulfill different dist_areas depending on what semester it was taken in. Let's just assume this doesn't happen

2018-05-14 00:20 UTC, churichard requested changes

2018-05-14 00:20 UTC, churichard commented on tigerpath/management/commands/tigerpath_get_courses.py
> +        self.stdout.write('course selection: courses scraped successfully')
Files should have newlines at the end

2018-05-14 00:20 UTC, churichard commented on tigerpath/views.py
> +    return HttpResponse(ujson.dumps(requirements, ensure_ascii=False), content_type='application/json')
Files should have newlines at the end

2018-05-14 00:20 UTC, churichard commented on tigerpath/scraper/scrape_all.py
>              if add_semester not in fetch_master.all_semesters:
Just wondering, are there cases where add_semester would actually already be in fetch_master.all_semesters?

2018-05-14 00:20 UTC, churichard commented on tigerpath/scraper/scrape_all.py
> +                if add_semester not in course.all_semesters:
This is always true

2018-05-14 00:20 UTC, churichard commented on tigerpath/scraper/scrape_all.py
> +            course.is_master = True
You forget to strip off the first 4 characters of the registrar_id. Might be better to move 
```python
# strip semester off id
course.registrar_id = course.registrar_id[4:]
course.is_master = True
course.save()
```
after this if block and the next else block, since it's in both.

2018-05-14 00:28 UTC, churichard commented
Also, in this latest code change, when the course number changes, doesn't the scraper just nuke the previous course number? Do you think it might be better to copy the course?

Actually, maybe that would be too complicated, because then we would have two courses with the same registrar id. Maybe we should have different cross listings based on the semester the course was offered in.

Or we can just assume that course number changes don't happen very often, and when it does, a student would know about the new course number. This is probably the simplest way to handle things, because it would require no change on your end.

2018-05-14 06:17 UTC, danielleung27 commented on tigerpath/scraper/scrape_all.py
>              if add_semester not in fetch_master.all_semesters:
Just in case we rescrape a semester it wont add a semester twice.

2018-05-14 06:24 UTC, danielleung27 commented
I think the 3rd option would be the best.

2018-05-14 16:04 UTC, churichard approved these changes

2018-05-14 16:15 UTC, merged