Logout Dropdown
TigerAppsOrg/TigerPath pull request #83
Opened 2018-05-13 19:27 UTC by adeniji19

Moved the logout option into a dropdown menu.

2018-05-13 19:38 UTC, churichard requested changes
You should put an arrow next to the netid. Try https://fontawesome.com/icons/caret-down?style=solid

2018-05-13 19:38 UTC, churichard commented on tigerpath/static/app/css/app-style.css
> +  height: calc(50vh - 60px);
Why did you change this?

2018-05-13 19:38 UTC, churichard commented on tigerpath/static/app/css/app-style.css
> +  height: calc(100vh - 95px);
Why did you change this?

2018-05-13 19:38 UTC, churichard commented on tigerpath/templates/tigerpath/index.html
> +      function dropFunction() {
Put this dropdown javascript code in a separate javascript file (in `tigerpath/static/app/js/dropdown.js` for example) and then load the script like this: `<script src="{% static 'app/js/dropdown.js' %}"></script>`

2018-05-13 19:48 UTC, adeniji19 commented on tigerpath/static/app/css/app-style.css
> +  height: calc(50vh - 60px);
minor fix for different screen sizes

2018-05-14 00:00 UTC, churichard approved these changes
I still think an arrow should be added to the name, but approving this for now.

2018-05-14 00:03 UTC, merged