Add CBE Major
TigerAppsOrg/TigerPath pull request #94
Opened 2018-05-15 05:51 UTC by danielleung27

2018-05-15 19:34 UTC, danielleung27 commented
Don't review yet, havent ran through schema checker.

2018-05-17 20:23 UTC, bnehoran requested changes

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +                    "explanation": "None",
Please don't use "None" for an explanation.

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +                    "explanation": "Noneervegrgergergerer",
What does this even mean????

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +                    "explanation": "Noneefafewfaweewgawegweafawefwefwae",
???????

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +                    "explanation": "Noneewfaefewfwegewgwegewgewgewfe",
????????

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +                    "explanation": "Noneewfdlkchweojfhnwesvjosdovojsevwioe",
??????

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +                    "explanation": "None",
Please don't use "None" for an explanation.

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +                    "explanation": "Noneewfdlkchweojfhnwesvjosdovojsevwioe",
?????

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +                    "explanation": "Noneewfaefewfwegewgwegewgewgewfe",
?????

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +                    "explanation": "Noneefafewfaweewgawegweafawefwefwae",
?????

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +                    "explanation": "Noneervegrgergergerer",
???

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +                    "explanation": "None",
Please don't use "None" for an explanation.

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +                    "explanation": "None",
Please don't use "None" for an explanation.

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +            "explanation": "None",
Please don't use "None" for an explanation.

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +            "explanation": "None",
Please don't use "None" for an explanation.

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +                    "explanation": "None",
Please don't use "None" for an explanation.

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +                    "explanation": "None",
Please don't use "None" for an explanation.

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +                "explanation": "None",
Please don't use "None" for an explanation.

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +            "explanation": "None",
Please don't use "None" for an explanation.

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +            "completed_by_semester": 8,
This is the default. No need to state explicitly.

This appears throughout, and should be removed, since it's just redundant.

2018-05-17 20:23 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +                "CBE 452"
Is Senior Independent Work handled properly here?

2018-05-17 20:27 UTC, bnehoran requested changes

2018-05-17 20:27 UTC, bnehoran commented on tigerpath/majors_and_certificates/majors/CBE_2018.json
> +            "dist_req]": "EM"
extra `]` in field name

2018-05-18 08:29 UTC, bnehoran approved these changes

2018-05-18 08:31 UTC, merged